export const effects = [
  ["blur", "Soft blur", "Basic"],
  ["sharpen", "Sharpen", "Basic"],
  ["brightness", "Brightness", "Basic"],
  ["contrast", "Contrast", "Basic"],
  ["saturation", "Saturation", "Basic"],
  ["exposure", "Exposure", "Basic"],
  ["vignette", "Vignette", "Basic"],
  ["grain", "Grain", "Texture"],
  ["noise", "Noise", "Texture"],
  ["glitch", "Signal glitch", "Creative"],
  ["rgb", "RGB split", "Creative"],
  ["aberration", "Chromatic edge", "Creative"],
  ["vhs", "Tape drift", "Texture"],
  ["film", "Film dust", "Texture"],
  ["glow", "Bloom", "Light"],
  ["neon", "Neon edge", "Light"],
  ["ripple", "Ripple", "Motion"],
  ["wave", "Wave", "Motion"],
  ["distortion", "Lens warp", "Motion"],
  ["shake", "Handheld", "Motion"],
  ["zoom", "Slow zoom", "Motion"],
  ["spin", "Spin", "Motion"],
  ["pixelate", "Pixelate", "Creative"],
  ["mosaic", "Mosaic", "Creative"],
  ["motionBlur", "Motion trail", "Motion"],
].map(([id, name, category]) => ({ id, name, category }));
